### ISSUE TITLE
Escape bug in nmo_lakeside

### ISSUE THREAD

**Issue by RPDGitHub** [nmrih/source-game#1016]
This bug occurs at the end of nmo_lakeside where you have to get to the boat.
If you move to the left of the small entrance that leads onto the boat you'll get stuck, which also causes the boat to become stuck. This resulted in survivors being overrun.

**Comment by Holycrapjimhox** [comment]
Mind recording a demo/video or share screenshots on how to reproduce the bug? It would help a lot.

**Comment by Holycrapjimhox** [comment]
I managed to perform the softlock.
Repro steps:

1) Wait until the chopper has opened the door
2) Run at the end of the boathouse, jump down the water
3) Run into the left corner where the boat comes close to the rocks at the shore
4) Hold W so that you infinitely move towards the corner even if the push trigger pushes you back
5) When the boat starts its turn, it will get stuck on you
6) Wait until the extraction timer runs out

**Comment by AtheistNMRiH** [comment]
fixed in r8855

**Comment by Holycrapjimhox** [comment]
Tested on r8863 and it's not fixed. You can still block the boat by jamming yourself in between the boat and one of the wood support beams. It prevents the boat from leaving:
![20180923012015_1](https://user-images.githubusercontent.com/35630284/45924113-c8215180-becd-11e8-9d90-97eb2d85612c.jpg)

Maybe hurt triggers could be used to mitigate this, but it would require testing since it could punish players too much for falling down the boat house.

**Comment by AtheistNMRiH** [comment]
probably fixed in r8864

**Comment by AtheistNMRiH** [comment]
as Holy Crap mentioned, he couldn't get to boat and get it stuck, so I guess this ticket should be closed
