### ISSUE TITLE
[public-1.10.0] nmo_broadway's train gets stuck with props

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1065]
You can softlock the map by placing most props in between the train doors before they close and then the train will not be able to move.

Steps to reproduce:
1) Unlock the extraction on nmo_broadway
2) Grab a prop like a pickaxe for example
3) Hold the item in your hands pressing E (the item must not enter your inventory)
4) Hold it in between the train doors
5) Wait until the doors close
6) The item will get stuck and the train will be unable to move

![8077405 400000001_20181224183009_1](https://user-images.githubusercontent.com/35630284/50406977-4206f680-07ad-11e9-841c-67820f87c0c7.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8887

**Comment by Holycrapjimhox** [comment]
I was able to still reproduce this issue in the current dev build unfortunately. At least, players can easily fix this by grabbing the stuck item. However, I recommend finding a proper solution, like adding a vphysclip in that spot.

**Comment by Holycrapjimhox** [comment]
Ignore the previous message, I mistakenly tested in an outdated dev build. Fix confirmed.
