### ISSUE TITLE
Zombies fail to freeze during the extraction cutscene

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#1100]
When zombies are overlapping at the start of the cutscene, they will fail their freeze schedule and remain unfrozen. These zombies will still attack and grab players meanwhile the player is unable to defend their self.

Holy Crap brought this up and said that the map nmo_urbanhazard is a good test map with its large number of runners spawning in the final courtyard.

**Comment by AtheistNMRiH** [comment]
![nmo_shit0000](https://user-images.githubusercontent.com/11333747/73455141-0d973e00-43a2-11ea-874a-6a6195812496.jpg)
I made a little test, added npc_template_maker and nmrih_game_state with input FreezeAllNpc, after that I killed two zombies, they despawned and weren't freezed (I don't know if nmrih_game_state uses same mechanic as for freezing during cutscene)

**Comment by essbuh** [comment]
This is not the same thing, extraction camera handles things differently. Not a valid repro case for this.

**Comment by Ryan-nmrih** [comment]
Looks like its caused by a zombie failing its freeze schedule which happens when zombies are overlapping at the time the cutscene starts playing. Some console output at time of bug:
```() Schedule (SCHED_NPC_FREEZE) Failed at 0!
() Schedule (SCHED_ZOMBIE_FAIL) Failed at 1!
() Schedule (SCHED_ZOMBIE_FAIL) Failed at 1!
() Schedule (SCHED_ZOMBIE_FAIL) Failed at 1!
() Schedule (SCHED_ZOMBIE_FAIL) Failed at 1!
```

Here's a map that lets you spawn zombies and start an extraction for testing.
[nmo_cutscenegrab.zip](https://github.com/nmrih/source-game/files/4137784/nmo_cutscenegrab.zip)

**Comment by essbuh** [comment]
Should be (mostly) fixed by code r4860

**Comment by Ryan-nmrih** [comment]
This issue is still present in latest dev build. I see some zombies freeze in their current animation state now which is a cool effect

**Comment by essbuh** [comment]
Should be fixed for realsy in src-r4904
