### ISSUE TITLE
[nms_notld] Picking up items through wall.

### ISSUE THREAD

**Issue by Denshin** [nmrih/source-game#165]
Upstairs in the bathroom it is possible to pick up the first aid kits through the wall when you sit on the bathtub. 

https://dl.dropboxusercontent.com/u/98282276/feedback/nmrih/1.jpg

**Comment by Winning117** [comment]
Glow implementation was redone which is linked to picking up items. Confirmed fixed in src-r4388/dev-r8769, needs to be closed.

**Comment by AtheistNMRiH** [comment]
glow change doesn't affect picking up items, issue isn't fixed

![nms_notld0000](https://user-images.githubusercontent.com/11333747/38161891-5e4882c0-3501-11e8-9815-1cab7818eed5.jpg)

**Comment by Winning117** [comment]
Weird, I tried on the bathtub and the glitch isn't present anymore.

**Comment by AtheistNMRiH** [comment]
oh sorry, didn't noticed that it is bathhub only, but it still persist in that shed

**Comment by AtheistNMRiH** [comment]
fixed in r8795

**Comment by Winning117** [comment]
Confirmed fixed in src-r4435/dev-r8795, needs to be closed.
