### ISSUE TITLE
[nmo_cabin] Wooden Rail on outside blocks bullets

### ISSUE THREAD

**Issue by badxreligion** [nmrih/source-game#330]
These wooden rails seem to be blocking gunfire.

![2013-08-09_00001](https://f.cloud.github.com/assets/5118109/941783/b322a554-0154-11e3-9ab6-f01317c7ac19.jpg)
![2013-08-09_00002](https://f.cloud.github.com/assets/5118109/941784/b321f988-0154-11e3-9380-18817ed10fb5.jpg)
![2013-08-09_00003](https://f.cloud.github.com/assets/5118109/941785/b3205862-0154-11e3-9a7e-1f0c0bd5a77d.jpg)

Fired the multiple x40ish times at zombies with the sks no hits.

**Comment by AtheistNMRiH** [comment]
fixed in r8729

**Comment by Winning117** [comment]
Tested in src-r4388/dev-r8769, confirmed fixed on the back side of the house toward the water but was not fixed for the front of the house. Needs to be reopened.

**Comment by AtheistNMRiH** [comment]
fixed in r8711

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8771, needs to be closed.
