### ISSUE TITLE
[nms_campblood] infinite player spawn after extraction cam death

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#540]
reminder for a solution/fix

**Comment by AtheistNMRiH** [comment]
potentially fixed in r8737

**Comment by Holycrapjimhox** [comment]
Tested on src-r4388/8771 and it's not fixed.
• When wave 10 finishes and the finale starts, all previously dead players will respawn without any tokens
• Any player that dies during the finale will respawn after a certain amount of time, detailed on-screen (no tokens)

**Comment by AtheistNMRiH** [comment]
daaamn

**Comment by Holycrapjimhox** [comment]
Tested on src-r4405/8775 and it's fixed. The report can be closed.
NOTE: You can't respawn during the finale even if you have respawn tokens. You die once and it's over.
