### ISSUE TITLE
Glitch on Broadway, making it impossible to continue. 

### ISSUE THREAD

**Issue by Dagendadragon** [nmrih/source-game#547]
Hello there!
Earlier I was playing on NMO_Broadway, the team and I got to the area past the cinema. (The second area? I dunno, I'm still very new to the game, and completely new to the terminology used for describing the maps.) 
Anyways. 
We were told to find the car battery, and put it into the truck. 
So the car battery is found, I'm carrying it. I drop it ontop of the fastex truck hood. 
When we opened the hood of the truck, the battery disappeared. 
After some searching, we realized it was inside of the cab of the truck. 
So while it was possible to grab and move it, we couldn't move it into its location. 
(The amount of swearing that was directed at me at this point was beautiful.) 

It was still movable from the outside, right, door. 
So if you made the window on the truck open, or something like that, it'd be possible to retrieve. 

If I didn't explain it clearly enough, let me know, and I'll do my best to explain it in more detail.

**Comment by Fersigal** [comment]
This bug is fixed i believe or is no bug at all, couldn't reproduce it, need confirmation of others

**Comment by AtheistNMRiH** [comment]
fixed in r8724

**Comment by Winning117** [comment]
![224260_20180403235847_1](https://user-images.githubusercontent.com/15934200/38293078-fe53c608-379a-11e8-9b66-b022c713cfd2.png)

Still issues with battery still not being able to be grabbed in truck.

**Comment by Winning117** [comment]
Confirmed fixed in atheist's new version, needs to be closed.

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8776, needs to be closed.
