### ISSUE TITLE
[public] Broadway2, invisible textures

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#933]
The staircase right after the sewer segment is not drawing textures for the landing treads.

![20180402022803_1](https://user-images.githubusercontent.com/11559683/38184409-cc05490c-361d-11e8-861b-e911a8ace966.jpg)

The same area in dev-r8770 shows checkerboard textures.

![20180402023414_1](https://user-images.githubusercontent.com/11559683/38184478-5f05d8de-361e-11e8-910e-dc2be97b1c23.jpg)

**Comment by Fersigal** [comment]
![image](https://user-images.githubusercontent.com/11538773/38191190-ff7c10d2-3667-11e8-93b6-81d99c18e924.png)

**Comment by AtheistNMRiH** [comment]
it was located in "billionlioe" folder, he replaced it recently

**Comment by Winning117** [comment]
Confirmed fixed in dev-r8777, needs to be closed.

**Comment by Dysphie** [comment]
I'm still getting nodraw stairs as of dev-r8849, not sure why.

**Comment by AtheistNMRiH** [comment]
![nmo_broadway20000](https://user-images.githubusercontent.com/11333747/44298458-a8ff3500-a30d-11e8-88f9-1924eebf77dc.jpg)

r8850
