### ISSUE TITLE
nmo_lakeside softlocks/out of bounds

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#950]
Version: src-r4405/dev-r8785

Wall of images as requested by Atheist :D

![224260_20180409220409_1](https://user-images.githubusercontent.com/15934200/38766523-36d014a6-3f88-11e8-8a18-2fbdd3d7711e.png)
![224260_20180409220717_1](https://user-images.githubusercontent.com/15934200/38766524-36e8677c-3f88-11e8-9a80-935b8323b971.png)
![224260_20180409221406_1](https://user-images.githubusercontent.com/15934200/38766525-36fea8fc-3f88-11e8-962f-19c707664e23.png)
![224260_20180409221734_1](https://user-images.githubusercontent.com/15934200/38766526-372507ae-3f88-11e8-88be-a204ec47491d.png)
![224260_20180409222213_1](https://user-images.githubusercontent.com/15934200/38766527-373ba16c-3f88-11e8-9574-5724b6577c65.png)
![224260_20180409223013_1](https://user-images.githubusercontent.com/15934200/38766528-375569bc-3f88-11e8-9951-6782a0752c2e.png)
![224260_20180409223103_1](https://user-images.githubusercontent.com/15934200/38766529-37730f6c-3f88-11e8-8651-4fc51574d247.png)
![224260_20180409223148_1](https://user-images.githubusercontent.com/15934200/38766530-3793cab8-3f88-11e8-892e-2eb986f7b6bf.png)
![224260_20180409223731_1](https://user-images.githubusercontent.com/15934200/38766531-37b5034a-3f88-11e8-9e18-43c6bdf305fb.png)
![224260_20180409224201_1](https://user-images.githubusercontent.com/15934200/38766532-37d4f498-3f88-11e8-9d3b-5c2d1562dd3e.png)
![224260_20180409224437_1](https://user-images.githubusercontent.com/15934200/38766533-37f5d0c8-3f88-11e8-93dd-96897d872e2e.png)
![224260_20180409225314_1](https://user-images.githubusercontent.com/15934200/38766534-3818e644-3f88-11e8-916d-a4c93411dfb5.png)
![224260_20180409225657_1](https://user-images.githubusercontent.com/15934200/38766535-383b7a74-3f88-11e8-97ed-bbb148132616.png)
![224260_20180409225659_1](https://user-images.githubusercontent.com/15934200/38766536-385d144a-3f88-11e8-88f1-50b13e019439.png)
![224260_20180409231201_1](https://user-images.githubusercontent.com/15934200/38766537-387f9574-3f88-11e8-9471-169d2bae7a8e.png)
![224260_20180409231223_1](https://user-images.githubusercontent.com/15934200/38766538-389b3b1c-3f88-11e8-9f26-ab777467d728.png)
![224260_20180409231932_1](https://user-images.githubusercontent.com/15934200/38766539-38e2f3c6-3f88-11e8-8e56-14a23d80a223.png)
![224260_20180409232235_1](https://user-images.githubusercontent.com/15934200/38766540-3904cf6e-3f88-11e8-8605-ba7ea1330c66.png)
![224260_20180409232243_1](https://user-images.githubusercontent.com/15934200/38766541-393957a2-3f88-11e8-8bf9-511aabf6fc28.png)
![224260_20180409232431_1](https://user-images.githubusercontent.com/15934200/38766542-395c9d3e-3f88-11e8-8b70-93cb585f557a.png)
![224260_20180409232519_1](https://user-images.githubusercontent.com/15934200/38766543-397dde18-3f88-11e8-8b1c-77641066a909.png)
![224260_20180409233124_1](https://user-images.githubusercontent.com/15934200/38766544-399ffa0c-3f88-11e8-9b42-528390e51655.png)
![224260_20180409233310_1](https://user-images.githubusercontent.com/15934200/38766545-39c38756-3f88-11e8-989e-8889ad3cf5bb.png)
![224260_20180409233427_1](https://user-images.githubusercontent.com/15934200/38766546-39e7f8f2-3f88-11e8-80be-f29866f55d4f.png)
![224260_20180409233846_1](https://user-images.githubusercontent.com/15934200/38766547-3a0af2ee-3f88-11e8-9ee0-70764fa329bb.png)
![224260_20180409234339_1](https://user-images.githubusercontent.com/15934200/38766548-3a2de10a-3f88-11e8-9ab9-fb17801248d1.png)
![224260_20180409235733_1](https://user-images.githubusercontent.com/15934200/38766549-3a5089da-3f88-11e8-9619-38165739f13c.png)
![224260_20180410002120_1](https://user-images.githubusercontent.com/15934200/38766550-3a73bce8-3f88-11e8-843f-0e6284098c20.png)
![224260_20180410002239_1](https://user-images.githubusercontent.com/15934200/38766551-3a961c20-3f88-11e8-9ade-6c23f4c8b2a9.png)
![224260_20180410003647_1](https://user-images.githubusercontent.com/15934200/38766552-3ab6e734-3f88-11e8-8bb2-0e3ba449caed.png)
![224260_20180410004049_1](https://user-images.githubusercontent.com/15934200/38766553-3ad8fcac-3f88-11e8-973e-f13bbd536925.png)
![224260_20180410004759_1](https://user-images.githubusercontent.com/15934200/38766554-3afceefa-3f88-11e8-9fb5-351394cf68d5.png)

**Comment by AtheistNMRiH** [comment]
fixed in r8788

**Comment by Winning117** [comment]
Tested in src-r4405/dev-r8788, following issues are still present.

![224260_20180419000834_1](https://user-images.githubusercontent.com/15934200/39027721-1d32ef1c-4408-11e8-86a5-a3d39bcd870d.png)
![224260_20180419000838_1](https://user-images.githubusercontent.com/15934200/39027722-1d4ba192-4408-11e8-8b0d-cdcfa2d433f1.png)
![224260_20180419001059_1](https://user-images.githubusercontent.com/15934200/39027723-1d63ed74-4408-11e8-9db2-f7c5c66bca1e.png)
![224260_20180419001304_1](https://user-images.githubusercontent.com/15934200/39027724-1d7cd302-4408-11e8-83b5-09601a6ffe84.png)
![224260_20180419001509_1](https://user-images.githubusercontent.com/15934200/39027725-1d95c01a-4408-11e8-8743-2fc2e8cf5c28.png)
![224260_20180419001629_1](https://user-images.githubusercontent.com/15934200/39027726-1db1debc-4408-11e8-89ee-df13523c1cb4.png)
![224260_20180419001822_1](https://user-images.githubusercontent.com/15934200/39027727-1dd3a16e-4408-11e8-95e2-150f52558a7e.png)
![224260_20180419002506_1](https://user-images.githubusercontent.com/15934200/39027728-1dfab808-4408-11e8-8e10-afdeaeb9cf43.png)
![224260_20180419002550_1](https://user-images.githubusercontent.com/15934200/39027729-1e23cf18-4408-11e8-8a33-38387f902546.png)
![224260_20180419002854_1](https://user-images.githubusercontent.com/15934200/39027730-1e4cac12-4408-11e8-84a2-8843f404e10e.png)
![224260_20180419003540_1](https://user-images.githubusercontent.com/15934200/39027732-1e759cd0-4408-11e8-9a25-7d27eb622eae.png)
![224260_20180419181055_1](https://user-images.githubusercontent.com/15934200/39027733-1e9d879a-4408-11e8-9c21-28143220280b.png)
![224260_20180419181611_1](https://user-images.githubusercontent.com/15934200/39027734-1ec4fe56-4408-11e8-8ad2-c8bb048e157a.png)
![224260_20180419181925_1](https://user-images.githubusercontent.com/15934200/39027735-1eefbaec-4408-11e8-9131-81cd1121590a.png)

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8789.
