### ISSUE TITLE
nms_campblood Map Issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#956]
Tested in src-r4405/dev-r8789. Just a few issues that allow the player to stand in the zone without taking damage and without the zone draining.
![224260_20180422003250_1](https://user-images.githubusercontent.com/15934200/39092593-4419edb4-45c6-11e8-9dda-8182b9faba3d.png)
![224260_20180422003550_1](https://user-images.githubusercontent.com/15934200/39092594-443259d0-45c6-11e8-9849-f7b6ada1f422.png)
![224260_20180422004015_1](https://user-images.githubusercontent.com/15934200/39092595-44472234-45c6-11e8-829d-e70176e46ffe.png)

**Comment by DDysphie** [comment]
>Zone doesn't drain if player stays here
Zones will drain even with players in them once the zombie count rises above a certain threshold (I think 12 NPCs). I don't think this is an issue.

**Comment by Winning117** [comment]
The threshold is dependent on the number of players so if a group of players stands up there the zone won’t drain. Also the canoe is being changed to be crushed when the player jumps on it. Having it nonsolid wouldn’t work since it covers a code.

**Comment by AtheistNMRiH** [comment]
fixed in r8791

**Comment by Winning117** [comment]
![224260_20180425235216_1](https://user-images.githubusercontent.com/15934200/39290231-caceb964-48e3-11e8-9080-c828ebccc512.png)
This is still an issue.
